### PR TITLE
Added UnHealthyHostCount metric + cleanup warnings

### LINKED ISSUE #3: Add unhealthy host count monitoring
This would be nice!

### PR DESCRIPTION
**Pull request by tovbinm**
Fixes https://github.com/lorenzoaiello/terraform-aws-alb-alarms/issues/3

### CODE REVIEW

**Comment by tovbinm** [comment]
Replaces https://github.com/lorenzoaiello/terraform-aws-alb-alarms/pull/2

**Comment by tovbinm** [comment]
ping

**Comment by tovbinm** [comment]
Ping @lorenzoaiello  ;)

**Review by lorenzoaiello — APPROVED** [review]
Looks good, thanks @tovbinm and sorry for the delay

**Pull request merged**
