### PR TITLE
Added HealthyHostCount alarm

### PR DESCRIPTION
**Pull request by tovbinm**

### CODE REVIEW

**Comment by lorenzoaiello** [comment]
Hey @tovbinm - Thanks for the PR.

Just curious - what's the use case for having an alarm fire when the healthy host count is _greater_ than zero? I could see one in case the healthy host count _equals_ zero.

**Comment by tovbinm** [comment]
Unfortunately `UnHealthyHostCount` metrics does not capture the case where a host (e.g. ECS Container) fails to start, since it never reaches Unhealthy state. Instead the container just bounces from Initial to Draining - https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html#target-health-states

Using `HealthyHostCount` lets you capture this.

**Comment by lorenzoaiello** [comment]
Gotcha, but in that scenario wouldn't you want to use `LessThanOrEqualToThreshold 0` instead of `GreaterThanThreshold 0`?

**Review by lorenzoaiello — APPROVED** [review]

**Comment by lorenzoaiello** [comment]
lgtm - thanks for the fix.

**Comment by tovbinm** [comment]
Thanks @lorenzoaiello !

It's also worth mentioning in the README that `target_group_id` and `load_balancer_id` should be set to use `tg.arn_suffix` and `lb.arn_suffix` respectively - e.g [[1](https://registry.terraform.io/providers/hashicorp%20%20/aws/latest/docs/resources/lb#arn_suffix)] and [[2](https://registry.terraform.io/providers/hashicorp%20%20/aws/latest/docs/resources/cloudwatch_metric_alarm#example-of-monitoring-healthy-hosts-on-nlb-using-target-group-and-nlb)]

**Pull request merged**
